apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: external-secrets
    version: 0.8.1
    namespace: external-secrets
    repo: https://charts.external-secrets.io
    releaseName: external-secrets
    valuesInline:
      installCRDs: true

resources:
  - vault.yaml
