apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
configMapGenerator:
  - behavior: merge
    literals:
      - |
        repository.credentials=- passwordSecret:
            name: github-secret
            key: token
          url: https://github.com/
          usernameSecret:
            name: github-secret
            key: user
      - "timeout.reconciliation=15s"
      - "kustomize.buildOptions=--enable-helm"
    name: argocd-cm
  - behavior: merge
    name: argocd-cmd-params-cm
    literals:
      - "server.insecure=true"
patches:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRoleBinding
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: default
resources:
  - namespace.yaml
  - https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.6.1
  - argocd.yaml
