apiVersion: apps/v1
kind: Deployment
metadata:
  name: cuteapp
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: cuteapp
  template:
    metadata:
      labels:
        app: cuteapp
    spec:
      containers:
        - name: cuteapp
          image: ghcr.io/5header/cuteapp:v0.0.10
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: cuteapp
spec:
  selector:
    app: cuteapp
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cuteapp
  labels:
    name: cuteapp
spec:
  ingressClassName: nginx
  rules:
    - host: cuteapp.kappalul.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: cuteapp
                port:
                  number: 80
