apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cuteapp
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cuteapp
    repoURL: https://github.com/wubbl0rz/CuteK8S
