apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://grafana.github.io/helm-charts"
    targetRevision: 2.9.9
    chart: loki-stack
    helm:
      releaseName: loki
      parameters:
        - name: grafana.sidecar.datasources.enabled
          value: "false"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: observe
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
