apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: cert-manager
    version: 1.10.0
    namespace: cert-manager
    releaseName: cert-manager
    repo: https://charts.jetstack.io
    valuesInline:
      installCRDs: true
resources:
  - namespace.yaml
  - cert-manager.yaml
